const express = require("express");
const userRoutes = require("./src/routes/user.route");
const roleRoutes = require("./src/routes/role.route");
const categoryRoutes = require("./src/routes/category.routes");
const serviceRoutes = require("./src/routes/service.pro.routes");
const productRoutes = require("./src/routes/product.routes");
const commonRoutes = require("./src/routes/common.routes");
const uploadRoutes = require("./src/routes/upload.route");
const customerRoutes = require("./src/routes/customer.routes");
const commandeRoutes = require("./src/routes/commande.routes");
const stripeRoutes = require("./src/routes/stripe.routes");
const reviewRoutes = require("./src/routes/review.routes");
const packagingRoutes = require("./src/routes/packaging.route");
const devisRoutes = require("./src/routes/devis.route");
const blogRoutes = require("./src/routes/blog.routes");
const supportRoutes = require("./src/routes/support.routes");
const recruitmentRoutes = require("./src/routes/recruitment.routes");
const searchRoutes = require("./src/routes/search.routes");
const boxRoutes = require("./src/routes/box.routes");
const commandBoxRoutes = require("./src/routes/commandbox.routes");
const machineRoutes = require("./src/routes/machine.routes");
const demandeMachineRoutes = require("./src/routes/demande-machine.routes");
const realtimeRoutes = require("./src/routes/realtime.routes");
const deliveryPricingRoutes = require("./src/routes/delivery-pricing.routes");

const app = express();
app.use("/user", userRoutes);
app.use("/role", roleRoutes);
app.use("/category", categoryRoutes);
app.use("/product", productRoutes);
app.use("/common", commonRoutes);
app.use("/service", serviceRoutes);
app.use("/upload", uploadRoutes);
app.use("/customer", customerRoutes);
app.use("/commande", commandeRoutes);
app.use("/stripe", stripeRoutes);
app.use("/review", reviewRoutes);
app.use("/packaging", packagingRoutes);
app.use("/devis", devisRoutes);
app.use("/blog", blogRoutes);
app.use("/support", supportRoutes);
app.use("/recruitment", recruitmentRoutes);
app.use("/box", boxRoutes);
app.use("/commandbox", commandBoxRoutes);
app.use("/machines", machineRoutes);
app.use("/demande-machine", demandeMachineRoutes);
app.use("/search", searchRoutes);
app.use("/realtime", realtimeRoutes);
app.use("/delivery-pricing", deliveryPricingRoutes);

module.exports = app;
